import Foundation

struct CurrencyData {
    let code: String
    let symbol: String
    let name: String
    
    static let allCurrencies: [CurrencyData] = [
        CurrencyData(code: "USD", symbol: "$", name: "US Dollar"),
        CurrencyData(code: "EUR", symbol: "€", name: "Euro"),
        CurrencyData(code: "GBP", symbol: "£", name: "British Pound"),
        CurrencyData(code: "JPY", symbol: "¥", name: "Japanese Yen"),
        CurrencyData(code: "CAD", symbol: "C$", name: "Canadian Dollar"),
        CurrencyData(code: "AUD", symbol: "A$", name: "Australian Dollar"),
        CurrencyData(code: "INR", symbol: "₹", name: "Indian Rupee"),
        CurrencyData(code: "CNY", symbol: "¥", name: "Chinese Yuan"),
        CurrencyData(code: "CHF", symbol: "Fr", name: "Swiss Franc"),
        CurrencyData(code: "NZD", symbol: "NZ$", name: "New Zealand Dollar"),
        CurrencyData(code: "SGD", symbol: "S$", name: "Singapore Dollar"),
        CurrencyData(code: "HKD", symbol: "HK$", name: "Hong Kong Dollar"),
        CurrencyData(code: "SEK", symbol: "kr", name: "Swedish Krona"),
        CurrencyData(code: "NOK", symbol: "kr", name: "Norwegian Krone"),
        CurrencyData(code: "DKK", symbol: "kr", name: "Danish Krone"),
        CurrencyData(code: "PLN", symbol: "zł", name: "Polish Złoty"),
        CurrencyData(code: "RUB", symbol: "₽", name: "Russian Ruble"),
        CurrencyData(code: "TRY", symbol: "₺", name: "Turkish Lira"),
        CurrencyData(code: "BRL", symbol: "R$", name: "Brazilian Real"),
        CurrencyData(code: "MXN", symbol: "Mex$", name: "Mexican Peso"),
        CurrencyData(code: "ZAR", symbol: "R", name: "South African Rand"),
        CurrencyData(code: "KRW", symbol: "₩", name: "South Korean Won"),
        CurrencyData(code: "TWD", symbol: "NT$", name: "New Taiwan Dollar"),
        CurrencyData(code: "THB", symbol: "฿", name: "Thai Baht"),
        CurrencyData(code: "MYR", symbol: "RM", name: "Malaysian Ringgit"),
        CurrencyData(code: "IDR", symbol: "Rp", name: "Indonesian Rupiah"),
        CurrencyData(code: "PHP", symbol: "₱", name: "Philippine Peso"),
        CurrencyData(code: "VND", symbol: "₫", name: "Vietnamese Dong"),
        CurrencyData(code: "AED", symbol: "د.إ", name: "UAE Dirham"),
        CurrencyData(code: "SAR", symbol: "﷼", name: "Saudi Riyal"),
        CurrencyData(code: "ILS", symbol: "₪", name: "Israeli New Shekel"),
        CurrencyData(code: "EGP", symbol: "E£", name: "Egyptian Pound"),
        CurrencyData(code: "PKR", symbol: "₨", name: "Pakistani Rupee"),
        CurrencyData(code: "BDT", symbol: "৳", name: "Bangladeshi Taka"),
        CurrencyData(code: "NGN", symbol: "₦", name: "Nigerian Naira"),
        CurrencyData(code: "KES", symbol: "KSh", name: "Kenyan Shilling"),
        CurrencyData(code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi"),
        CurrencyData(code: "CLP", symbol: "CL$", name: "Chilean Peso"),
        CurrencyData(code: "COP", symbol: "CO$", name: "Colombian Peso"),
        CurrencyData(code: "PEN", symbol: "S/", name: "Peruvian Sol"),
        CurrencyData(code: "ARS", symbol: "AR$", name: "Argentine Peso"),
        CurrencyData(code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia"),
        CurrencyData(code: "RON", symbol: "lei", name: "Romanian Leu"),
        CurrencyData(code: "CZK", symbol: "Kč", name: "Czech Koruna"),
        CurrencyData(code: "HUF", symbol: "Ft", name: "Hungarian Forint"),
        CurrencyData(code: "BGN", symbol: "лв", name: "Bulgarian Lev"),
        CurrencyData(code: "HRK", symbol: "kn", name: "Croatian Kuna"),
        CurrencyData(code: "RSD", symbol: "дин.", name: "Serbian Dinar"),
        CurrencyData(code: "ISK", symbol: "kr", name: "Icelandic Króna"),
        CurrencyData(code: "KZT", symbol: "₸", name: "Kazakhstani Tenge"),
        CurrencyData(code: "QAR", symbol: "﷼", name: "Qatari Riyal"),
        CurrencyData(code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar"),
        CurrencyData(code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar"),
        CurrencyData(code: "OMR", symbol: "﷼", name: "Omani Rial"),
        CurrencyData(code: "JOD", symbol: "د.ا", name: "Jordanian Dinar"),
        CurrencyData(code: "LBP", symbol: "ل.ل", name: "Lebanese Pound"),
        CurrencyData(code: "MAD", symbol: "د.م.", name: "Moroccan Dirham"),
        CurrencyData(code: "DZD", symbol: "د.ج", name: "Algerian Dinar"),
        CurrencyData(code: "TND", symbol: "د.ت", name: "Tunisian Dinar"),
        CurrencyData(code: "LYD", symbol: "ل.د", name: "Libyan Dinar"),
        CurrencyData(code: "SDG", symbol: "ج.س.", name: "Sudanese Pound"),
        CurrencyData(code: "ETB", symbol: "Br", name: "Ethiopian Birr"),
        CurrencyData(code: "UGX", symbol: "USh", name: "Ugandan Shilling"),
        CurrencyData(code: "TZS", symbol: "TSh", name: "Tanzanian Shilling"),
        CurrencyData(code: "MUR", symbol: "₨", name: "Mauritian Rupee"),
        CurrencyData(code: "MOP", symbol: "MOP$", name: "Macanese Pataca"),
        CurrencyData(code: "MMK", symbol: "K", name: "Myanmar Kyat"),
        CurrencyData(code: "KHR", symbol: "៛", name: "Cambodian Riel"),
        CurrencyData(code: "LAK", symbol: "₭", name: "Lao Kip"),
        CurrencyData(code: "MNT", symbol: "₮", name: "Mongolian Tögrög"),
        CurrencyData(code: "NPR", symbol: "₨", name: "Nepalese Rupee"),
        CurrencyData(code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee"),
        CurrencyData(code: "MVR", symbol: "ރ", name: "Maldivian Rufiyaa"),
        CurrencyData(code: "BND", symbol: "B$", name: "Brunei Dollar"),
        CurrencyData(code: "FJD", symbol: "FJ$", name: "Fijian Dollar"),
        CurrencyData(code: "PGK", symbol: "K", name: "Papua New Guinean Kina"),
        CurrencyData(code: "SBD", symbol: "SI$", name: "Solomon Islands Dollar"),
        CurrencyData(code: "TOP", symbol: "T$", name: "Tongan Paʻanga"),
        CurrencyData(code: "VUV", symbol: "VT", name: "Vanuatu Vatu"),
        CurrencyData(code: "WST", symbol: "WS$", name: "Samoan Tālā"),
        CurrencyData(code: "XPF", symbol: "₣", name: "CFP Franc"),
        CurrencyData(code: "XAF", symbol: "FCFA", name: "Central African CFA Franc"),
        CurrencyData(code: "XOF", symbol: "CFA", name: "West African CFA Franc"),
        CurrencyData(code: "XCD", symbol: "EC$", name: "East Caribbean Dollar"),
        CurrencyData(code: "BBD", symbol: "Bds$", name: "Barbadian Dollar"),
        CurrencyData(code: "JMD", symbol: "J$", name: "Jamaican Dollar"),
        CurrencyData(code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar"),
        CurrencyData(code: "BZD", symbol: "BZ$", name: "Belize Dollar"),
        CurrencyData(code: "GYD", symbol: "G$", name: "Guyanese Dollar"),
        CurrencyData(code: "SRD", symbol: "SR$", name: "Surinamese Dollar"),
        CurrencyData(code: "BMD", symbol: "BD$", name: "Bermudian Dollar"),
        CurrencyData(code: "KYD", symbol: "CI$", name: "Cayman Islands Dollar"),
        CurrencyData(code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder"),
        CurrencyData(code: "AWG", symbol: "ƒ", name: "Aruban Florin"),
        CurrencyData(code: "BSD", symbol: "B$", name: "Bahamian Dollar"),
        CurrencyData(code: "CUP", symbol: "$", name: "Cuban Peso"),
        CurrencyData(code: "DOP", symbol: "RD$", name: "Dominican Peso"),
        CurrencyData(code: "HTG", symbol: "G", name: "Haitian Gourde"),
        CurrencyData(code: "PAB", symbol: "B/.", name: "Panamanian Balboa"),
        CurrencyData(code: "PYG", symbol: "₲", name: "Paraguayan Guaraní"),
        CurrencyData(code: "UYU", symbol: "$U", name: "Uruguayan Peso"),
        CurrencyData(code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar"),
        CurrencyData(code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano"),
        CurrencyData(code: "CRC", symbol: "₡", name: "Costa Rican Colón"),
        CurrencyData(code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal"),
        CurrencyData(code: "HNL", symbol: "L", name: "Honduran Lempira"),
        CurrencyData(code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba"),
        CurrencyData(code: "SVC", symbol: "₡", name: "Salvadoran Colón"),
        CurrencyData(code: "BAM", symbol: "KM", name: "Bosnia and Herzegovina Convertible Mark"),
        CurrencyData(code: "ALL", symbol: "L", name: "Albanian Lek"),
        CurrencyData(code: "MKD", symbol: "ден", name: "Macedonian Denar"),
        CurrencyData(code: "MDL", symbol: "L", name: "Moldovan Leu"),
        CurrencyData(code: "GEL", symbol: "₾", name: "Georgian Lari"),
        CurrencyData(code: "AMD", symbol: "֏", name: "Armenian Dram"),
        CurrencyData(code: "AZN", symbol: "₼", name: "Azerbaijani Manat"),
        CurrencyData(code: "BYN", symbol: "Br", name: "Belarusian Ruble"),
        CurrencyData(code: "TJS", symbol: "ЅM", name: "Tajikistani Somoni"),
        CurrencyData(code: "TMT", symbol: "m", name: "Turkmenistani Manat"),
        CurrencyData(code: "UZS", symbol: "so'm", name: "Uzbekistani Som"),
        CurrencyData(code: "KGS", symbol: "с", name: "Kyrgystani Som"),
        CurrencyData(code: "AFN", symbol: "؋", name: "Afghan Afghani"),
        CurrencyData(code: "IRR", symbol: "﷼", name: "Iranian Rial"),
        CurrencyData(code: "IQD", symbol: "ع.د", name: "Iraqi Dinar"),
        CurrencyData(code: "SYP", symbol: "£", name: "Syrian Pound"),
        CurrencyData(code: "YER", symbol: "﷼", name: "Yemeni Rial"),
        CurrencyData(code: "BIF", symbol: "FBu", name: "Burundian Franc"),
        CurrencyData(code: "CDF", symbol: "FC", name: "Congolese Franc"),
        CurrencyData(code: "DJF", symbol: "Fdj", name: "Djiboutian Franc"),
        CurrencyData(code: "ERI", symbol: "Nfk", name: "Eritrean Nakfa"),
        CurrencyData(code: "RWF", symbol: "RF", name: "Rwandan Franc"),
        CurrencyData(code: "SOS", symbol: "S", name: "Somali Shilling"),
        CurrencyData(code: "SSP", symbol: "£", name: "South Sudanese Pound"),
        CurrencyData(code: "SZL", symbol: "L", name: "Swazi Lilangeni"),
        CurrencyData(code: "ZMW", symbol: "ZK", name: "Zambian Kwacha"),
        CurrencyData(code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar"),
        CurrencyData(code: "NAD", symbol: "N$", name: "Namibian Dollar"),
        CurrencyData(code: "MWK", symbol: "MK", name: "Malawian Kwacha"),
        CurrencyData(code: "MGA", symbol: "Ar", name: "Malagasy Ariary"),
        CurrencyData(code: "SCR", symbol: "₨", name: "Seychellois Rupee"),
        CurrencyData(code: "KMF", symbol: "CF", name: "Comorian Franc"),
        CurrencyData(code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra"),
        CurrencyData(code: "CVE", symbol: "$", name: "Cape Verdean Escudo"),
        CurrencyData(code: "GMD", symbol: "D", name: "Gambian Dalasi"),
        CurrencyData(code: "GNF", symbol: "FG", name: "Guinean Franc"),
        CurrencyData(code: "LRD", symbol: "L$", name: "Liberian Dollar"),
        CurrencyData(code: "SLL", symbol: "Le", name: "Sierra Leonean Leone"),
        CurrencyData(code: "MRO", symbol: "UM", name: "Mauritanian Ouguiya"),
        CurrencyData(code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya"),
        CurrencyData(code: "SHP", symbol: "£", name: "Saint Helena Pound"),
        CurrencyData(code: "FKP", symbol: "£", name: "Falkland Islands Pound"),
        CurrencyData(code: "GIP", symbol: "£", name: "Gibraltar Pound"),
        CurrencyData(code: "IMP", symbol: "£", name: "Manx Pound"),
        CurrencyData(code: "JEP", symbol: "£", name: "Jersey Pound"),
        CurrencyData(code: "GGP", symbol: "£", name: "Guernsey Pound"),
        CurrencyData(code: "AOA", symbol: "Kz", name: "Angolan Kwanza"),
        CurrencyData(code: "CDF", symbol: "FC", name: "Congolese Franc"),
        CurrencyData(code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi"),
        CurrencyData(code: "KES", symbol: "KSh", name: "Kenyan Shilling"),
        CurrencyData(code: "NGN", symbol: "₦", name: "Nigerian Naira"),
        CurrencyData(code: "TZS", symbol: "TSh", name: "Tanzanian Shilling"),
        CurrencyData(code: "UGX", symbol: "USh", name: "Ugandan Shilling"),
        CurrencyData(code: "ZAR", symbol: "R", name: "South African Rand"),
        CurrencyData(code: "ZMW", symbol: "ZK", name: "Zambian Kwacha"),
        CurrencyData(code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar")
    ]
    
    static func getCurrencyData(for code: String) -> CurrencyData? {
        return allCurrencies.first { $0.code == code }
    }
} 